name: aztest
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gymnasium
  - ipykernel
  - pytorch
  - tqdm
  - numpy
  - tensorboard
  - graphviz
  - python-graphviz
  - matplotlib
  - wandb
  - seaborn
  - pip
  - pip:
    - torchrl
    - "gymnasium[toy-text]"
